version: "3.5"

networks:
  localdev:
    name: localdev

services:
  angular-service: 
      container_name: angularcontainer  
      build: src/cadastro-conta-app 
      volumes: 
        - './usr/app' 
      ports: 
        - '4200:4200' 
      command: >
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
  main-api:
    build: src/cadastro-conta-wepapi/
    restart: always
    ports:
      - '5000:5000'
    depends_on: 
      - mongo
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"